### ISSUE TITLE
Dyskusja 02 - wolność

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/kognizastoneur#10]
Zapraszam wszystkich do dyskusji na temat wolności.
Czy jesteśmy wolni? Czy determinizm to dla nas wyrok czy też furtka do wolności? Jakie są warunki abyśmy coś/kogoś nazwali wolnym?
Czy kompatybilizm ma sens? Jakie konsekwencje prawne i społeczne mają odkrycia neuronauki na temat naszej wolności?

**Comment by alegowski** [comment]
Znalazłem artykuł rozwodzący się na temat czy wolna wola jest iluzją i bardzo spodobało mi się konkluzja do której dochodzi autor i jak ją tłumaczy. Przedstawił to w następujący sposób : kiedy chcę szybko mrugnąć okiem, zmieniam chwilowo prawa fizjologiczne, które bez mojej woli podążają jakimś biologicznym cyklem mrugnięć. Moja interwencja w organiczną prawidłowość powoduje że moja powieka będzie mrugać szybciej bądź wolniej niż by to robiła bez niej. Robiąc w ten sposób nie łamie praw natury a tylko podporządkowuje je swojej intencji. Bez obecności natury (ciała) nie jestem w stanie wykonać czynności a więc moja wola oddziaływuje na naturę lecz nie może istnieć bez niej. Intencjonalna wola jednostki nastawionej na cel nie może zostać zredukowana do fenomenu praw natury, lecz potrzebna nam jest bardziej zaawansowana struktura sterująca, wprowadzająca cel i jedność całemu systemowi . I właśnie to wiąże się z czymś więcej niż tylko "edytowaniem produktów" bezpośredniej fizycznej przyczynowości. Mam nadzieje ze udało mi się dobrze uchwycić sens :) Polecam przeczytanie całego artykułu w oryginale http://web.a.ebscohost.com/ehost/pdfviewer/pdfviewer?sid=62feeabd-5107-44d2-8b35-4f8169af6c95%40sessionmgr4004&vid=1&hid=4106

**Comment by wzanczak** [comment]
Wrzucam krótki filmik, który jest przyjemnym podsumowaniem tematu wolnej woli, chociaż co do tego że ,,jeśli mamy prawo do decydowania o pewnych aspektach naszego życia ( co zjemy, gdzie wyjdziemy na wakacje itp.) to znaczy, że mamy wolną wolę'' , nie do końca się zgadzam. To są po prostu wybory i nasze preferencje ale życie stawia nam też wiele ograniczeń i nie do końca możemy robić ,,to co chcemy''. Ale to tylko moja opinia, więc zerknijcie na filmik ( jest krótki) i powiedzcie, co o tym sądzicie.
--->    [https://www.youtube.com/watch?v=bDkLUBdvOkw](url) (skopiujcie i wklejcie w pasku, bo przez link czasem nie chce wchodzić)

**Comment by mmagnuski** [comment]
@alegowski
Nie mam teraz dostępu do tego artykułu, ale z tego jak go opisujesz wynika, że autor zakłada dualizm (ja jest czymś spoza ciała i natury). Klasyczne problemy takiego stanowiska to:
- w jaki sposób zachodzą interakcje między tymi dwoma światami?
- jakimi prawami rządzi się świat substancji umysłowej i w jaki sposób jego działanie zapewnie lepszy substrat dla wolności niż "zwykła" materia?
  Bez odpowiedzi na te pytania taki opis wolności wyboru cały czas brzmi jak "and then magic happens". :)

**Comment by sgrabowska** [comment]
@wzanczak Nie mogę uchwycić jak się nazywa ten facet, który wypowiada się w filmiku. Generalnie fajnie tłumaczy czym jest materializm. Ja z kolei chciałam się podzielić moją myślą na temat determinizmu. Szukałam jakiegoś porównania, dzięki któremu mogłabym to lepiej zrozumieć. Doszłam do następującego: determinizm przypomina mi trochę religię. Zakładam, że coś/ktoś już ułożył dla świata jakiś plan. Ten ktoś/coś/świat (trudno określić co konkretnie) wie już wszystko co było i co będzie i ja mam pełne zaufanie, że właśnie tak jak się dzieje, ma być. I w tym wyraża się moim zdaniem wolność w tym ujęciu. Tym, że nie wiem co mnie czeka, ale mam zaufanie, że decyzje które podejmuję prowadzą mnie do czegoś co miało być, co było przewidziane i mam zaufanie, że wszystko nie dzieje się bez przyczyny i po coś jest. Jest to jakiś wkład, cegiełka w coś większego. Bo może mnie samej nie pomoże/nie wzbogaci itd., ale kto wie, może przyniesie coś 6 pokoleniu po mnie. Nie wiem, czy to dobre rozumienie i czy nie zakręciłam zanadto :)

**Comment by mmagnuski** [comment]
@sgrabowska to jest raczej fatalizm. W determinizmie nie zakładamy, że jest jakikolwiek plan, tylko że prawa fizyki określają w całości przyszłość, tzn że prawa te nie są probabilistyczne. Determinizm można traktować bardzo pesymistycznie, nie mając zaufania co do swojej przyszłości oraz lękając się jakimi torami pójdą bezlitosne trybiki kosmosu. Bo nawet jeżeli przyszłość jest w całości zdeterminowana przez stan teraz to, nie mamy pojęcia jak się potoczy, bo ani nie znamy stanu teraz (stan całego wszechświata co do każdej cząstki elementarnej) ani nie mamy pełnej wiedzy praw (wliczając w to, że nie mamy wciąż pewności czy ich natura jest deterministyczna czy nie). Jakimś przybliżeniem takiej perspektywy jest stan gdy dzieciaki w klasie czekają na ogłoszenie wyników sprawdzianu. Oceny zostały już wystawione na kartkach dawno temu, ale każde dziecko myśli sobie "byle nie 1" albo "oby było 5", trzymając za to w myśli kciuki niemal jakby to był rzut kostką. Wydaje mi się że tak po prostu działamy że (na jakimś poziomie) niepewność naszej wiedzy jest dla nas porównywalna z niepewnością samych praw, które generują zjawiska, z których czerpiemy tę wiedzę.

**Comment by mmagnuski** [comment]
@wzanczak Filmik jest rzeczywiście fajnie zrobiony, ale oferuje bardzo duże uproszczenia w dodatku w taki sposób aby nachalnie zaoferować jakiś konkretny światopogląd. Jeżeli dodacie sobie po każdym zdaniu, w którym ten gość przedstawia coś jako oczywisty fakt zamiast kropki znak zapytania - zobaczycie, że w zasadzie w każdym punkcie, o którym mówi można (a może nawet należałoby mieć) wątpliwości.

**Comment by oborkowska** [comment]
Mnie mocno irytuje zastanawianie się nad tym, czy człowiek ma, czy nie ma wolnej woli, przez co trudno mi się włączyć do ogólne dyskusji. Myślę, że może się to brać trochę ze strachu. Mi wolna wola daje sens życia, więc jeżeli wolnej woli nie mam, to nie widzę za bardzo sensu w tym, żeby odgrywać jakąś rolę, na którą nie mam wpływu.

Może to jest tak, że wolna wola jest tylko złudzeniem, które sprawia, że czujemy sens w naszym istnieniu i działaniu, i że po prostu to złudzenie zostało nam zaprogramowane w trakcie ewolucji, jako przydatne (tu nawiązuję do teorii o self z trzecich zajęć). 

Ale tak czy siak, wolę przyjąć, że po prostu tę wolną wolę mam. Mimo tego, że jest to trochę nierzetelne podejście, a raczej wygodne.

**Comment by marek123271** [comment]
Uważam że człowiek ma wolną wolę, a jego życie nie jest zewnęcznie zdeterminowane. Gdyby tak było to wszystkie nasze wybory, tak nie, za i przeciw, nie miały by sensu i prowadziły by do tego samego rozwiązania. 
Ale wracając do wolnej woli, wszyscy ja mamy, ale jak pokazuje psychologia społeczna możemy ją chwilowo stracić, przyznać komuś rację jednocześnie wiedząc że jej nie ma, (Eksperyment Ascha). Czy komformizm nie jest zrzekaniem sie wolnej woli jednostki w zamian za akceptacje społeczną?
A odwrotnie, dlaczego człowieka naprawdę wolnego, człowieka który w swej wolności nie niepodporządkowywuje się zasadą społecznym społeczeństwo każde i odrzuca (ostracyzm).  
Tak naprawdę każdy z nas jest odrobinę zniewolony przez otaczające społeczeństwo, ale dzięki temu zniewoleniu wspólnie działamy i osiągamy zyski.

**Comment by wzanczak** [comment]
@mmagnuski oczywiście, że na końcu każdego zdania, trzeba postawić znak zapytania. Nie można upraszczać tematu świadomości, czy wolnej woli do kilkuminutowego filmiku. Zgadzam się z tym w 100%.
Zgadzam się też z Markiem, że wszyscy jesteśmy trochę ,,zniewoleni'' ale też uważam, że mimo wszystko w większości spraw mamy prawo i wolność w decyzjach.

**Comment by mmagnuski** [comment]
@oborkowska, @marek123271, @wzanczak 
Jestem ciekaw jak rozumiecie tę wolność - tzn z czego wynika i na czym polega w kontekście mózgu?
Czy uważacie że ta wolność jest sprawą natury czy wymaga czynników supernaturalnych?

BTW, warto poczytać sobie Stanford Encyclopedia of Philosophy:
http://plato.stanford.edu/entries/freewill/

**Comment by kajalaura** [comment]
Jeśli chcecie dokładniej zrozumieć na czym polega determinizm, to bardzo polecam ten artykuł :)
[Artykuł](https://github.com/mmagnuski/kognizastoneur/files/182158/ContentServer.pdf)
Jeśli o mnie chodzi, determinizm przemawia do mnie dużo bardziej niż indeterminizm. Kojarzy mi się to trochę z kosmosem - ludzki umysł nie jest w stanie objąć wielkości wszechświata, jest to dla nas aż absurdalne, że coś może być tak olbrzymie, a my w tym wszystkim tacy mali. Stawiamy się w centrum wszechświata, bo nie potrafimy spojrzeć na siebie z perspektywy jakiegoś ziarnka piasku w morzu pustyni (a nawet atomu, jeśli by patrzeć na wielkość). Wydaje mi się, że tak samo jest z wolną wolą i prawami wszechświata. Nigdy nie będziemy w stanie objąć zasad nim rządzących (ani ich poznać w 100%), więc wmawiamy sobie, że mamy wpływ na cokolwiek. A tak naprawdę nasze zachowania to tylko jedna z niewyobrażalnej ilości zasad rządzących wszechświatem i wszystkim co się w nim zawiera. I wydaje mi się, że można z tym żyć, tak samo jak z tym, jak mali jesteśmy w stosunku do kosmosu. Bo po prostu nie potrafimy sobie tego wyobrazić, więc nam z tym dobrze ;) Taka wygodna niewiedza. I wątpię, żeby ewolucja dała jakiemukolwiek organizmowi we wszechświecie umiejętność zrozumienia tego wszechświata i jego zasad.
Ah, jak filozoficznie. :D

**Comment by mmagnuski** [comment]
@kajalaura (i reszta)
Mam podobną perspektywę, ale chciałem tylko przypomnieć nam wszystkim, że kwestia wolności woli i kwestia determinizmu/indeterminizmu są w zasadzie rozłączne. Czy za ostateczny kształt naszych myśli i zachowania odpowiada bezlitosny porządek praw wszechświata, czy też dodatkowo wkrada się jakaś losowość (np. na poziomie kwantowym) - jesteśmy w równym stopniu 'zniewoleni' tymi mechanizmami. Już nie mówiąc o tym, że praktycznie, w naszym codziennym życiu, oba scenariusze są nierozróżnialne. Kluczowa jest kwestia wyjaśnienia co mogłoby znaczyć "(ja) jestem wolny" czyli co to jest to ja, które miało by być wolne i co to jest ta wolność, którym owo ja miałoby się szczycić. Siłą rzeczy dualiści i moniści będą mieć inne odpowiedzi na to pytanie (przynajmniej pod kątem owego _ja_).

**Comment by mmagnuski** [comment]
BTW, @kajalaura `Pakistan Journal of Social Sciences`? :grinning:

**Comment by kajalaura** [comment]
@mmagnuski artykuł jest dobrze napisany, plus to przeglądówka (czy jak to tam nazwać) :D Sugerujesz, że w Pakistanie są gorsi w pisaniu przeglądowek? :P
Ja jestem za tym, że nie jesteśmy wolni nawet pod kątem myśli i zachowań i że są one determinowane naszym otoczeniem, czyli w ostateczności wszechświatem.

**Comment by mmagnuski** [comment]
@kajalaura Nie chodzi mi o to, że miałby być gorszy, ale że nieźle wygrzebałaś. :)

**Comment by oborkowska** [comment]
Ja myślę, że z z tym zagadnieniem wolnej woli może być tak pół na pół. Tzn.: mamy zbiór mozliwości, z których możemy wybrać*\* unikalne **zachowanie czy posunięcie. Ale ten zbiór jest już **zdeterminowany** poprzez nasze wszystkie wcześniejsze wybory i środowisko. Ale to jest trochę takie koło, bo w sposób trochę wolny (bo jeszcze środowisko) wybieramy w każdym momencie, jakie będą nasze kolejne możliwości. Nie wiem, czy w miarę jasno to przedstawiłam.
Dla mnie to jest trochę supernaturalne, ale tylko dlatego, że tak jak pisała @kajalaura nie jesteśmy sami w sobie w stanie zrozumieć i wytłumaczyć wszystkich zjawisk. Tzn.: ostatecznie wierzę, że to są jakieś prawa fizyki, czy czegokolwiek, co jest w stanie to wytłumaczyć, i że to wszystko jest jakoś spójne.
Trudne są dla mnie te rozważania, dlatego tak trochę chaotycznie wychodzą mi odpowiedzi.

**Comment by wzanczak** [comment]
@mmagnuski Moim zdaniem, to właśnie posiadanie świadomości i wolnej woli czyni człowieka ,,supernaturalnym''. Nie wiem czy działa to na odwrót, czyli że supernaturalne czynniki sprawiają, że mamy wolną wolę. Wydaje mi się, że raczej nie ma tutaj magii. Głównie czynniki społeczne oraz to jak stymulowany jest ludzki mózg sprawia, że mamy ,,poczucie'' wolnej woli. Wydaje mi się, że bardziej niż magia, pasuje tu słowo tajemnica.

**Comment by marek123271** [comment]
Nasza wolność ogranicza się do wolnej woli, która i tak jest ograniczona np. ograniczenia związane z fizyką, ale myślę że większość ludzi nie zdaje sobie sprawy z tych ograniczeń, tzn. przyjmuje je za naturalne, bo są od zawsze, natomiast filozofia znosi te ograniczenia, przynajmniej teoretycznie, i daje człowiekowi poczucie wolności myślenia, co jest dobrym początkiem do dalszego rozwoju. Te właśnie filozowiczne rozważania sa czyms więcej niż nam dała natura, sa czymś ponadnaturalnym co pozwala człowiekowi poczuć się wyjątkowo jako gatunek żyjący na tej samej planecie z innymi gatunkami zwierząt. Ale czy mamy rację w tym stawianiu sie wyżej? Nie podejrzewam innych gatunków o poglądy filozoficzne, ale mogę się mylić. 
Ale wszystkie nasze rozważania i filozofiie (w tym te o wolności) i tak mają początek w naszym mózgu, więc są wynikiem działania bardzo złożonego, lecz naturalnego systemu.

**Comment by oborkowska** [comment]
@marek123271 czy dobrze rozumiem, że odbierasz nasze filozoficzne rozważania jako coś supernaturalnego. Ale biorą się z naszego naturalnego mózgu. Czyli, naturalny/fizyczny/racjonalny/wytłumaczalny(nie dla nas) narząd mózgu jest tak zaprogramowany, aby łączyć nas z czymś supernaturalnym??

**Comment by marek123271** [comment]
@oborkowska Tak, z mojego punktu widzenia nasze rozważania są supernaturalne, uważam że jesteśmy jedynym gatunkiem zdolnym do filozofii, a zawdzięczmy to właśnie specyficznej, innej niż u innych gatunków budowie mózgu. Cała nasza kultura jest czymś supernaturalnym, czymś co nie mogła by wytworzyc sama natura, ale bez natury kultura by nie powstała. Więc cała nasza kultura i nauka jest zależna od biologii(budowy naszego mózgu), i stara się znaleść i wykorzystac zawsze 1% więcej możliwości niż w tej chwili pozwala na to natura, w ten sposób kształtując ewolucję.

**Comment by mmagnuski** [comment]
Drodzy, 
przyda nam się definicja `supernaturalności`. Ja rozumiałem ten termin jako "niemożliwe do pełnego wyjaśnienia przez czynniki materialne (fizyczne, chemiczne, fizjologiczne)". Jeżeli naszą kulturę zawdzięczamy naszej naturze tzn. np. budowie naszych mózgów, to w tym sensie nie będzie supernaturalna. Bez wątpienia gatunek ludzki jest niezwykły, ale jeszcze nie umiemy przechodzić przez ściany ;)

**Comment by mmagnuski** [comment]
Chciałem jeszcze gorąco wszystkim polecić ten tekst:
http://plato.stanford.edu/entries/compatibilism/

**Comment by sgrabowska** [comment]
A jest jakieś podejście, które mówi, że wiadomo co było a to co będzie zależy jak ja i moje decyzje zderzą się z "innymi kwantami"? Bo ja jestem zwolennikiem takiego podejścia :) Że wolność przejawia się w tym, że ja jako jednostka i moje decyzje pośrednio wpływają na to jak dalej będzie wyglądał świat.. Coś jak w "Podaj dalej" tylko w pełnym wymiarze a nie tylko w aspekcie dobrych uczynków.

**Comment by mmagnuski** [comment]
@sgrabowska 
Myślę, że można powiedzieć, że kompatybilizm jest właśnie takim podejściem. Tzn. "może nasze decyzje są w pełni zdeterminowane przez przeszłość / stan wszechświata, ale właśnie przez to decyzje te uczestniczą w łańcuchu przyczyn i skutków, oddziałując na nasze zachowanie, a w efekcie - przyszłość wszechświata". Ale samych kompatybilizmów jest trochę.

**Comment by mmagnuski** [comment]
Inne rozwiązania będą już musiały zakładać np. dualizm, a przez to supernaturalne oddziaływania substancji umysłowej (czymkolwiek by była) na stany fizycznego wszechświata. John Eccles na przykład uważał, że ja (umysł/dusza) jest "z innego świata" (tzn. niefizyczne, był dualistą) i wpływa na zachowanie poprzez oddziaływanie na kwantowe procesy podczas wypuszczania neuroprzekaźników. Dla mnie takie podejście bez wyjaśnienia problemów dualizmu, o których pisałem wcześniej, to jest właśnie stwierdzenie "and then magic happens" czyli brak wytłumaczenia zjawiska. Ale niektórych może przekonuje.

**Comment by kmortas** [comment]
Tak się teraz zaczęłam zastanawiać:

czy to nie paradoks, że nasza wolna wola wpływa na życie innych i tym samym ich wolną wolę? Jak tak człowiek trochę dłużej nad tym się zastanowi, to aż się może zakręcić w głowie :) Dodatkowo: jako osoba religijna wierzę w istnienie Boga i od zawsze wierzyłam w to, że sprawuje on kontrolę nad podstawowymi prawami natury. A skoro na człowieka natura potrafi wpływać w różnoraki bezpośredni sposób, to czy jesteśmy tak faktycznie wolni...?

**Comment by mgrzebalski** [comment]
zgadzam się z Mikołajem co do stwierdzenia, że nawet zakładając determinizm, nie możemy się w 100% przygotować na jutro. Wspomniana niepewność, niepełna wiedza, a przede wszystkim nasze ograniczenia poznawcze jak min. pamięć oraz wiążąca się z nią ograniczona zdolność do przetwarzania informacji, nie mówiąc o zawężeniu uwagi związanym z sytuacją stresową, wiodą nas na manowcei oraz mogą skutecznić utrudnić dokonanie słusznej decyzji. Na osi wolna wola vs. determinizm uważam się bezpiecznie za agnostyka B)
Z tym, że skłaniam się w kierunku kompatybilizmu, więc nie uważam za konieczne by taką oś tworzyć. Staram się mieć w świadomości, że nawet opisanie w sposób deterministyczny tego co nas spotyka i spotkało będzie niczym innym jak zwerbalizowaniem i logicznym sformułowaniem doświadczeń, tego co ludzkości udało się zaobserwować. Przyjąć coś za pewnik w tym kontekście to tak jak podczas gry w ruletkę obstawić czerwony kolor, gdy kilka razy z rzędu wypadł nam czarny, zapominając, że ruletka niestety/na całe szczęście nie jest obdarzona pamięcią.
Odnośnie istnienia wolnej woli, sądzę, że najlepsza odpowiedź brzmiałaby : "to zależy...". Dokładniej mówiąc, ja myślę, że kwestia leży w nazewnictwie. Potencjały gotowości w sygnale EEG pozwalają na predykcję wykonania ruchu wolincjonalnego jeszcze do 0,5 sekundy przed świadomym stwierdzeniem osoby badanej, że ruch ona ten zaraz wykona. Ja wolną wolą nazywam surowo "polem manewru", sposobnością do zachowania zgodnego z naszymi wartościami i moralnością przy wymienionych ograniczeniach jak pamięć, uwaga, niepełna wiedza, niepewność etc.

**Comment by mmyszkowska** [comment]
Weronika napisała, że determinizm przypomina jej religię, mi z kolei indeterminizm przypomina religię bo jest idealistyczny, zakłada istnienie czegoś oderwanego od zasady przyczyny i skutku co w moim odczuciu opiera się na życzeniowym podejściu. Oczywiście uważam, że mamy duży wpływ na swoje życie, ale coś (często nawet coś w nas samych, poza czynnikami zewnętrznymi) determinuje czy podejmujemy próby wpływu czy nie (i z jakim efektem), zaś ta zmienna jest zdeterminowana m.in. przekonaniami, osobowością, w tym zarówno wrodzonymi tendencjami jak i tymi nabytymi w doświadczeniu oraz tymi ukształtowanymi przez nas samych w toku samodoskonalenia, znowu to w jakim stopniu się samodoskonalimy ma swoją przyczynę, a więc jest zdeterminowane m.in. tym jakie jest nasze poczucie sensu takiego działania, ile poświęciliśmy na to czasu, jakie są wrodzone możliwości poznawcze itd). Determinizm w odniesieniu do ludzi nie oznacza, że człowiek nie może decydować co robi i że dokonując danego wyboru nie można było wybrać inaczej tylko to, że choć można było to dany człowiek i tak nie wybrałby inaczej, bo coś jest przyczyną tego jaki to będzie wybór (np. przekonania, osobowość, doświadczenia, potrzeby, wpływ różnych czynników zewnętrznych itd.) Podobnie determinizm nie może być usprawiedliwieniem czyichś przewinień, bo mówi nie tyle, że człowiek nie miał wyjścia, tylko tyle że mając cały wachlarz możliwości nie postąpiłby inaczej niż postąpił, bo dana czynność ma swoją przyczynę (np. leżącą w złośliwości czy zaniedbaniu danej osoby). Próbując przechytrzyć ten mechanizm i wykazać się wolną wolą możemy wykonać różne akcje, które są też zdeterminowane (chęcią obejścia mechanizmu, zaś ta chęć jest zdeterminowana osobistymi właściwościami jak potrzeba wolności, tendencje do przekory itp. i czynnikami zewnętrznymi –np. wyzwalacz w postaci rozmowy o braku wolnej woli która do tego prowokuje .  Tak samo jak w przypadku świadomości –jeśli chcemy dyskutować o obecności wolnej woli to wszystko zależy od jej definicji. Można powiedzieć, ze wolna wola istnieje jako możliwość wyboru, ale także że nie istnieje w takim sensie że nie pozbędziemy się czegoś co powoduje powstanie danego wyboru i dyktuje to, że w jego miejsce nie pojawił się inny wybór. 
Pozwolę sobie dodać na koniec trochę absurdu  Jak to bywa w fizyce, każdą prawidłowość rozpatruje się dla standardowych warunków, więc determinizm również rozpatrywałabym w tych kategoriach, co za tym idzie dopuszczam zaistnienie jakiegoś warunku który naruszyłby fundamentalną zasadę determinizmu, jednak według mnie, wolna wola (czy też to co tak odczuwamy) w jej powszechnie znanej postaci mieści się w kategorii „warunki standardowe”. Ponadto wszystko zależy od perspektywy: patrząc na to co nam najlepiej znane można mieć wrażenie, że indeterministyczna wolność istnieje, bo każdy ją subiektywnie odczuwa. Z perspektywy wszechświata można dojść do deterministycznych wniosków obserwując przyczynę i skutek we wszystkim co kiedykolwiek podlegało obserwacjom, a więc to co jest nam choć trochę znane, z jeszcze szerszej perspektywy przyjmującej np. wiele wszechświatów, nieliniowość czasu itd. determinizm zaczyna znowu ustępować miejsca indeterminizmowi w wyścigu po wiarygodność i sens logiczny. Jeszcze szerzej szukając odpowiedzi, znowu determinizm wraca do łask, bo jeśli mogą istnieć pewne odstępstwa od przyczyny i skutku w klasycznym rozumieniu albo warunki w których dawny pewnik czy dane prawo fizyki nie zadziała, to czy nie dlatego, że zadziałało inne prawo które na to pozwoliło? Możliwe też, że te terminy wcale nie wykluczają się i można założyć istnienie zarówno chaotycznej przypadkowości jak i deterministycznego porządku, a ich jednoczesne choć niekoniecznie łączne występowanie uzasadnić różnicą w definiowaniu, perspektywą odniesienia (np. to co nam znane vs to co nas w ogóle nie dotyczy), typowością warunków itd. Ponoć Einstein stwierdził kiedyś, że o ile przeciwieństwem płytkiej prawdy jest kłamstwo to przeciwieństwem głębokiej prawdy jest inna głęboka prawda. Patrząc natomiast już nie z drugiej a z n-tej strony, deterministyczne sekwencje mogą być elementem większego chaosu lub przypadkowość i chaos może być ograniczonym elementem deterministycznej rzeczywistości jak kępka krzaków na stepie i jego istnienie w określonych ryzach może mieć swoje uwarunkowania i zakres (niekoniecznie w znaczeniu miejsca w przestrzeni). Pytanie wtedy w którym kawałku, której rzeczywistości jesteśmy my ze swoją wolną wolą (lub jej brakiem) i czy przypadkiem tej rzeczywistości też nie obejmuje coś szerszego, co czyni z niej skromną enklawę na podobieństwo fraktali ;D 
Wracając do nauki ze spektrum filozoficznych dywagacji przesyłam link do artykułu w którym przedstawiono polemikę z wynikami badania pozwalającego przewidzieć decyzje uczestników zanim je podejmą:
http://biotechnologia.pl/bioetyka/aktualnosci/czy-wolna-wola-istnieje,313
Pomimo, że raczej bliżej mi do deterministycznych koncepcji, to zgadzam się z tym, że to badanie nie podważa jeszcze wolnej woli. Dodałabym jeszcze od siebie, że dla tego eksperymentu duże znaczenie może mieć też fakt jaką czynność wykonuje uczestnik. Jeśli stara się on po prostu wygenerować coś przypadkowego (jak ruch dowolnej ręki w dowolnym momencie) i ta decyzja nie jest dla niego ważna, a więc nie wymaga uwagi czy nawet świadomości dokonywanego wyboru (wręcz świadomość jest niewskazana skoro zachowanie ma być przypadkowe) to proces generowania takiej akcji będzie automatyczny przez co późno sobie uświadomi podjęcie decyzji w stosunku do czasu kiedy mózg już określił jaka będzie czynność. W przypadku decyzji wymagających wzmożonej uwagi, świadomego przetworzenia wielu informacji i będących ważnych z punktu widzenia potrzeb jednostki, czas w którym z sygnału można odczytać moment podjęcia decyzji mógłby już nie być tak rozbieżny z czasem uświadomienia sobie dokonanego wyboru.
