### ISSUE TITLE
Dyskusja 03 - ewolucja

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/kognizastoneur#11]
Zaczynamy kolejny temat - ewolucję.

Czy dobrze pamiętam, że @wzanczak jest Strażniczką Platformy na ten tydzień?
Czy potrzeba kogoś dolosowac do platformy?

**Comment by wzanczak** [comment]
Taak, ten tydzień jest mój. A co do losowania kogoś jeszcze, to jak uważasz.

**Comment by wzanczak** [comment]
Z racji tego, że nie było mnie na zajęciach tydzień temu, to trudno mi się odnieść do tego o czym na nich dyskutowaliście. Czy macie jakieś wątki, które chcielibyście tu rozwinąć?
Jeśli nic się nie pojawi na platformie przez najbliższe kilka godzin, to podrzucę jakiś temat :)

**Comment by mmagnuski** [comment]
Poruszyć można:
- jakiś wątek z rozdziału - rozdział był pisany w 2005 więc, od tego czasu
  trochę się mogło zmienić.
- świadomość (i wolność) w kontekście ewolucji
- psychologię ewolucyjną
  I co tam jeszcze chcesz.

## 

---

**Comment by oborkowska** [comment]
Ja dzisiaj się dowiedzialam, że u ludzi jest różnica (w stosunku do innych gatunkow) w falach theta. 
Jeszcze nie zdazylam nic konkretnego się dowiedzieć, ale z chęcią bym się dowiedziala:)
Mogę podrzucic badanie, ale najwczesniej w piatek.

**Comment by wzanczak** [comment]
Ja pamiętam, że kiedyś mnie bardzo zastanawiało to , że między gryzoniami i ludźmi jest w sumie nieznaczna różnica. U człowieka czestotliwość fal theta wynosi 4-7Hz a u gryzoni 3-12Hz. 
Jeśli będziesz miała ten artykuł, to ja bardzo chętnie przeczytam! :)

**Comment by wzanczak** [comment]
Ciekawa jestem, jakie jest wasze zdanie na temat altruizmy w świetle psychologii ewolucyjnej. Jeżeli celem człowieka powinno być maksymalizowanie zysków i zadbanie o przedłużenie gatunku, to altruizm jest pewnym zaprzeczeniem. Altruiści wydają się tu być odchyleniem od normy poprzez chęć ,,dawania'',, nawet własnym kosztem. Z drugiej strony, na drodze ewolucji wiele gatunków nauczyło się współpracy, więc może altruistami są ludzie, którzy lepiej czują się działając na rzecz innych i po prostu nie potrzebują niczego w zamian. Może to jest dla nich też forma ,,współpracy''. Trochę zagmatwałam ale mam nadzieję, że mniej więcej wiecie o co mi chodzi.

**Comment by wzanczak** [comment]
A propos jutrzejszych zajęć : [http://news.discovery.com/tech/robotics/realistic-robot-lady-cheerfully-agrees-to-destroy-humans-160322.htm?utm_source=Facebook.com&utm_campaign=DiscoveryChannel&utm_medium=social&sf22986804=1]
Trochę to przerażające...

**Comment by mmyszkowska** [comment]
Osobiście spotkałam się ze stwierdzeniem, że altruizm w „najczystszej” postaci jest zawsze szkodliwy dla jednostki , ponieważ ukierunkowuje jej siły i zasoby na pomoc innym, zamiast  egoistycznie koncentrować je na maksymalizowaniu jej własnego dobra. Z logicznego punktu widzenia można by, więc stwierdzić, że altruizm jest „ewolucyjnym niewypałem” i powinien być on wyeliminowany. W rzeczywistości altruizm ma się jednak dobrze, a jego przejawy obserwujemy wśród przedstawicieli wszystkich gatunków społecznych. Dlaczego? Może dlatego, że „realny altruizm” jest zawsze, w mniejszym lub większym stopniu egoistyczny, a przez to bardziej „naturalny”. Może to trochę zagmatwane, ale już tłumaczę.

Chodzi mi o to, że w przypadku tzw. altruizmu twardego(zwanego także altruizmem krewniaczym bądź genetycznym) osobnik będzie tym bardziej skory do pomocy, im większe będzie podobieństwo genetyczne między nim, a osobnikiem potrzebującym pomocy. W uproszczeniu: dbając o przetrwanie genów swoich krewnych, egoistycznie dbasz także o przetrwanie swoich własnych.

Nawet w przypadku altruizmu miękkiego (wzajemnego), który przez badaczy utożsamiany jest z tzw. „czystym altruizmem” można doszukać się przejawów egoizmu. Mimo, że w tym wypadku jesteśmy skorzy nieść pomoc wszystkim osobnikom w danej populacji, to jednak ostateczna decyzja o udzieleniu pomocy zależy od tego, czy istnieją realne widoki na rewanż ze strony danej jednostki, bądź danej społeczności. Pomagamy innym, ponieważ spodziewamy się, że w ten sposób zwiększymy swoje (i naszych krewnych) przyszłe szanse na uzyskanie pomocy i niejako przyczynimy się do stworzenia społeczności, w której generalnie można liczyć na pomoc innych.

W rezultacie zarówno w przypadku altruizmu twardego, jak i miękkiego uzyskujemy pewne korzyści, które zwiększają szanse jednostki, populacji bądź całego gatunku na sukces ewolucyjny. Trudno więc mówić tutaj o prawdziwej bezinteresowności. Z drugiej strony tak przedstawiony altruizm przestaje być "dewiacją behawioralną", a staje się całkiem skutecznym narzędziem, które ma zapewnić naszym genom przetrwanie.

**Comment by wzanczak** [comment]
Jeśli patrzeć na altruizm w kategoriach dopuszczających pewną ,,cząstkę egoizmu'', to się z Tobą zgadzam. To jest zdecydowanie bardziej ludzkie podejście. Myślę, że nie ma na świecie ,,prawdziwych altruistów'' a nawet jeśli wydaje im się, że nimi są, to bardziej brakuje im pewnej świadomości. Chociaż to tylko moje zdanie...

**Comment by sgrabowska** [comment]
Hej nie mogę się powstrzymać, żeby nie wrzucić tego tutaj.. choć pewno już słyszeliście o Tay: http://tvn24bis.pl/tech-moto,80/tay-chatbot-microsoftu-publikowal-rasistowskie-tweety,630054.html
Nie wiem kto przy zdrowych zmysłach pozwolił się uczyć programowi od ludzi w sieci, bo przy odrobinie refleksji rezultat był do przewidzenia. Wiadomo, że ogólnie to lubimy (my ludzie) sobie w necie pohejtować na dużą  skalę... Ciekawe jak to jest przydatne w kontekście ewolucji heh Może celem jest wykluczenie słabych. Jak w Sparcie (po bandzie). Eliminacja słabych jednostek za pomocą hejtu.

**Comment by marek123271** [comment]
Czasami zachowanie zwierząt wyglada na altruistyczne, np. nietoperze oddające część swojego pozywienia głodnym nietoperzą ze stada którym nie powiodło sie na polowaniu. Ale zachowanie to nie jest do końca altruistyczne, nietoperz oddający pożywienie wie że inny członek stada zachowa się tak samo w stosunku do niego, w analogicznej sytuacji. Altruizm nie jest do końca zły dla jednostki, raczej procentuje na przyszłość zapewniając przetrwanie pomimo niepowodzenia.

Co ciekawe, u tych samych nietoperzy wystepuje mechanizm niepomagania niepomagającym, więc nawet tak małe społeczeństwo podzielone jest na współpracujących i radzących sobie samemu. 
Moim zdaniem jest to przykłąd że altruizm nie jest do końca bezinteresowny, a raczej jest to zachowanie społeczne które ma na celu pomoc swojej grupie, czyli także w pewien sposób sobie.

**Comment by mmyszkowska** [comment]
Zainteresowanych tematem zachowań altruistycznych wśród nietoperzy odsyłam do badania: “Food sharing in vampire bats: reciprocal help predicts donations more than relatedness or harassment”
Link: http://rspb.royalsocietypublishing.org/content/280/1753/20122573

Co ciekawe w przypadku zwierząt społecznych, jak np. wspomnianych nietoperzy w odstawkę poszły kwestie pokrewieństwa. We wspomnianych badaniu nietoperze chętniej niż własnym krewniakom pomagały nietoperzom, które w przeszłości wyświadczyły im jakąś przysługę, nawet niekoniecznie związaną z dzieleniem się pożywieniem. Wskazuje to na pewną ewolucyjną tendencję, która w sprzyjających warunkach sprowadza się do zastępowania altruizmu twardego altruizmem miękkim. W przypadku nietoperzy, mimo iż nadal są one genetycznie uwarunkowane by troszczyć się o swoich krewniaków, to jednak w procesie socjalizacji skłonność ta została do pewnego stopnia stłumiona i zastąpiona zachowaniami korzystniejszymi dla całej społeczności

Interesujący jest fakt, że tendencja ta wydaje się być na tyle uniwersalna, że pojawia się ona zarówno wśród mniej, jak i bardziej zaawansowanych istot społecznych.

Łatwo odnieść się tu do przykładu nas samych – ludzi. O ile każdemu z nas leży na sercu dobro naszych krewnych, to jednak łatwo jest zauważyć, że w naszym społeczeństwie altruizm twardy tolerowany jest tylko do pewnego stopnia, ponieważ „ślepy” altruizm genetyczny mógłby zakłócić istniejący porządek społeczny i działać na niekorzyść całej populacji bądź gatunku. Stąd pewnie wzięło się ogólne (i w pełni zrozumiałe) społeczne potępienie nepotyzmu oraz ruchów, które stawiają konkretną nację bądź rasę ponad innymi.

**Comment by muliasz** [comment]
Mimo, iż nie wykluczam możliwości, że od czasu do czasu w każdej populacji pojawiają się jednostki w pełni bezinteresowne i naturalnie skore do zachowań altruistycznych, to jednak wydaje mi się, że w większości bylibyśmy skłonni uznać, że w naturze dużo łatwiej o postawę egoistyczną. Jak to więc możliwe, że grupa egoistycznych jednostek wyewoluowała w społeczność aktywnie propagującą altruizm wzajemny?

Wydaje mi się, że odpowiedź na to pytanie możemy znaleźć po przeanalizowaniu tzw. „konfliktu więźnia” – problemu kojarzonego z teorią gier. W wersji skróconej:
Mamy dwóch obcych sobie więźniów pozbawionych możliwości kontaktowania się. Zeznania jednego mogą obciążyć drugiego i odwrotnie. Więźniowie mogą współpracować poprzez zachowanie milczenia (obaj odsiedzą tylko 6 miesięcy) lub zdradzić zeznając. Jeśli zdradzi tylko jeden, będzie on wolny, a jego towarzysz zostanie skazany na 10 lat więzienia. Jeśli zdradzą obaj, obaj odsiedzą po 5 lat. Oczywiście w przypadku pojedynczej rozgrywki obserwowano głównie postawę egoistyczną.

Szczególnie interesujące były jednak wyniki uzyskane w przypadku „interowanego dylematu więźnia”, gdzie Ci sami gracze grali ze sobą wielokrotnie. Po przeanalizowaniu wyników zauważono, że dopóki gra obliczona była na konkretną liczbę podejść wśród graczy dominowała postawa egoistyczna, ponieważ zawsze istniała opcja zdrady bez żadnych konsekwencji w ostatniej rundzie. W przypadku nieokreślonej liczby rund dominowała tendencja do wytworzenia i utrzymania stanu równowagi, jaką była współpraca.

Wychodzi na to, że wraz z tworzeniem społeczności jednostki zaczynają myśleć bardziej przyszłościowo i odpowiednio modyfikują własne zachowanie i najczęściej obierają strategię, która przejawia się zachowaniami altruistycznymi. Czy są one jednak bezinteresowna? Nie wydaje mi się. Jednostka taka zmuszona do życia wśród konkretnych jednostek przez bliżej nieokreślony czas zwyczajnie boi się ich odwetu, jakim mogłoby być np. nieudzielenie pomocy lub nawet wykluczenie ze społeczności. Dodatkowo należy pamiętać, że pokorna współpraca jednostki może w przyszłości zaprocentować.

**Comment by mmagnuski** [comment]
Hej, fajnie że podłapaliście temat altruizmu. Zastanawiam się tylko czy gdy piszecie o "prawdziwym altruizmie" - nie macie na myśli przepadkiem jakiegoś zachowanie na tyle wyidealizowanego, że niemożliwego do zrealizowania w naszym świecie. Pozwolę sobie zacytować za wikipedią definicję altruizmu:

> zachowanie polegające na działaniu na korzyść innych. Według J. Poleszczuka polega ono na dobrowolnym ponoszeniu pewnych kosztów przez jednostkę na rzecz innej jednostki lub grupy, przeciwstawne zachowaniu egoistycznemu[1].

To, że jednostka ponosi koszty na rzecz innej jednostki/grupy nie znaczy wcale, że w dalszej perspektywie (średnio) nie zwraca się taka inwestycja (tzn. atruizm może być altruizmem nawet jeżeli koszty się zwracają). Ponadto, nawet jeżeli zachowania takie zostały ukształtowane przez selekcję naturalną  - wcale nie znaczy to, że z punktu widzenia jednostki nie będą one motywowane "odruchem serca", a tylko czystą kalkulacją. Odruchy serca to w końcu też ewolucyjnie ukształtowane mechanizmy.

**Comment by wzanczak** [comment]
A jak myślicie, jak podejście psychologii ewolucyjnej mówiące o przetrwaniu gatunku ma się do obecnych czasów? Bo o ile dla zwierząt reprodukcja jest czymś naturalnym, instynktownym, to zastanawia mnie jak to odnieść do ludzi. Wydaje mi się, że ludzie bardziej myślą teraz o samorealizacji i zaspokajaniu własnych potrzeb, niekoniecznie mają związek z przedłużaniem gatunku. Coraz mniej kobiet rodzi dzieci a nawet jeśli rodzą, to z reguły jest to ,,przypadek''. Podobno w Polsce za 30 lat liczba urodzeń ma spaść nawet o 24% ( informacje z GUS'u).Czy w takim razie procesem adaptacyjnym będziemy nazywać zaspokajanie własnych ( wyższych)potrzeb, a ,,podstawowe'' przedłużanie gatunku nie będzie już tak ważne? Wiem, że to wszystko jest pewnie bardziej złożone ale pojawiło mi się taki pytanie w głowie i chciałam się z Wami podzielić i zapytać, co o tym sądzicie?

**Comment by wzanczak** [comment]
@mmagnuski jeśli chodzi o altruizm, to nie traktuje go w sposób wyidealizowany. Oczywiście, działanie na rzecz jednostki (nawet ponosząc pewne koszty) nie jest niczym dziwacznym. Jednak zastanawiające jest to jak wykształcił się ten ,,odruch serca'' i kiedy zaczęła zanikać czysta potrzeba zysku i przetrwania za wszelką cenę. Pewnie ma to związek z układem limbicznym i z ewolucją sfery emocjonalnej... hmm jeśli ktoś czytał albo kojarzy jakiś artykuł  na ten temat, to poproszę :)

**Comment by muliasz** [comment]
Odnosząc się do twojej ostatniej wypowiedzi, wydaje mi się, że wspomniany „odruch serca”, czyli  - w moim odczuciu -  połączenie empatii i altruizmu, należy powiązać z ewolucją kory przedczołowej (zainteresowanych tematem odsyłam do mojej i Magdy prezentacji), a szczególności z wykształceniem i rozwojem obszaru znanego pod nazwą - dorsomedial prefrontal cortex (DMPFC). Obszar tez w ścisłej  współpracy z układem limbicznym pozwala osobnikowi wczuć się na poziomie emocjonalnym w sytuację innego osobnika, a stąd już tylko krok do udzielenia pomocy potrzebującemu (w szczególności gdy pomoc nie jest obciążona zbyt dużym kosztem).

Ciekawe, że w tym samym czasie do głosu może dojść także ośrodek DLPFC, czyli dorsolateral prefrontal cortex (DLPFC), odpowiedzialny m.in. za nie emocjonalną kalkulację zysków i strat oraz tzw. zdroworozsądkowe myślenie.

Wychodzi, więc na to, że w toku ewolucji dryfowaliśmy jednocześnie w dwóch przeciwnych kierunkach i ostatecznie uzyskaliśmy pewien „zdrowy” poziom równowagi, gdzie potrafimy dostosować się do norm narzuconych przez społeczeństwo, współpracować i prezentować zachowania altruistyczne, a jednak jesteśmy na tyle egoistyczni, że nie w ostatecznym rozrachunku stracimy na tych działaniach.

W kwestii czegoś do przeczytania na ten temat, zachęcam do zerknięcia na (The origin of altruizm):
https://www.psychologytoday.com/blog/prefrontal-nudity/201307/the-origin-altruism

(Pisałam tutaj głównie o ludziach, naszych krewniakach i przodkach, ale spróbuję znaleźć coś, co pomoże mi odnieść się do innych zwierząt, zwłaszcza tych, u których nie wykształciła się kora przedczołowa).

**Comment by mulinska** [comment]
Zdecydowanie widać zmianę własnych potrzeb o których pisała Weronika. Jednak nie wiem jak to odnieść do psychologii ewolucyjnej. Myślę, że w dużej mierze jest to spowodowane tym, iż w końcu zmienione zostało postrzeganie roli kobiety. Kiedyś głównym celem kobiety, była reprodukcja i wychowanie dziecka. Natomiast w dzisiejszych czasach kobiety nie muszą się podporządkowywać swoim "ewolucyjnym" rolom i w końcu mają wybór. ( ciężko mi jest ująć moją myśl, żeby nie zabrzmiała źle...)
Według badań przeprowadzonych przez CBOS powodów dla których kobiety nie decydują się na potomstwo, bądź opóźniają pojawienie się potomstwa, jest kilka: głównym powodem jest poczucie, że cała odpowiedzialność spada na nie. Obawiają się, że nie będzie je stać na dziecko, bądź boją się problemów w pracy. Kolejnym problemem jest brak odpowiednich partnerów. Na ten temat możecie przeczytać wywiad z Prof. Szlendakiem. (http://wyborcza.pl/1,76842,17243450,Prof__Szlendak__Kobiety_nie_decyduja_sie_na_dzieci_.html)
Ale nie wiem czy rzeczywiście można powiedzieć, że to samorealizacja będzie procesem adaptacyjnym a przedłużanie gatunku stanie się mniej ważne?
Dodatkowo jestem ciekawa co sądzicie o praktyce zamrażania komórek jajowych, która staje się coraz bardziej popularna (wspomina o tym prof. Szlendak w wywiadzie).

**Comment by oborkowska** [comment]
To jest bardo ciekawy temat. Zgadzam się z wytłumaczeniami prof. Szlendak. Myślę, że przedłużenie gatunku będzie zawsze najważniejsze i do tego będzie dążyć nasze społeczeństwo, i że po prostu prędzej czy później, będzie funkcjonowała w większej ilości państw rzeczywistość, w której kobiety i mężczyźni mogą się rozwijać, żyć godnie i jednocześnie spokojnie rozmnażać się i wspólnie wychowywać potomstwo. Nie wiem tylko, na ile to jest moje wyidealizowane myślenie na ten temat, a na ile można powiedzieć, że jest to jakiś trend w podejściu ludzi.

**Comment by jourix** [comment]
Słuchajcie, zupełnie przypadkiem kilka dni temu udało mi obejrzeć się film Children of Men - http://www.imdb.com/title/tt0206634/ film przedstawia przerażającą wizję świata, w której w 2027 roku okazuje się, że ludzie na całym świecie stali się bezpłodni. Koniecznie obejrzyjcie, film skłania do myślenia (poza tym wciąga i jest bardzo dobrze nakręcony).
W moim przypadku spowodował zmianę myślenia w kwestii do posiadania potomstwa przez ludzi, szczególnie w kontekście ostatnich trendów, o których mówicie powyżej.
Do tej pory wydawało mi się, że przedłużanie gatunku jest ważne z punktu widzenia przetrwania gatunku, nie koniecznie szczęścia jednostki. Jednak ten film pokazał mi, że nawet jeżeli nie chcemy mieć własnych dzieci i jest to nasz świadomy wybór, do indywidualnego poczucia sensu życia i szczęścia potrzebujemy dzieci innych ludzi. Rozmnażanie i przedłużanie gatunku jest niezbędne do poczucia sensu i motywacji dla każdego z nas. Człowiekowi, jako istocie społecznej, do samorealizacji potrzebni są inni ludzie. Zatem samorealizacja jako taka jest mocno połączona z przedłużeniem gatunku. Nawet jeżeli osobiście nie chcemy się mieć potomstwa (ok, każdy ma wolną wolę) nie możemy zapominać, że dzieci (ogólnie) są potrzebne każdemu z nas. Spełnionej, samotnej staruszce/starcowi jest potrzebny ktoś kto zrobi obiad, poda leki czy zmieni pampersa. A będzie to osoba, której całe życie poświęciła "jakaś Matka". Myślę, że przedłużanie gatunku jest w interesie każdego z nas, niezależnie od indywidualnych preferencji związanej z posiadaniem dziecka. 
Ciekawa jestem co myślicie na ten temat?

**Comment by kmortas** [comment]
@jourix 
Co do tego, że 'przedłużanie gatunku jest w interesie każdego z nas, niezależnie od indywidualnych preferencji związanej z posiadaniem dziecka' - i tak  i nie :) Wiele osób wychodzi z założenia, że i tak za te kilkadziesiąt lat odejdą z tego świata i nie będą się musieli martwić, czy rodzi się coraz mniej dzieci... To tak jak z podejściem do ochrony środowiska.

**Comment by sgrabowska** [comment]
Ciekawy wątek. Oglądałam ten film parę lat temu, nie wywarł na mnie tak piorunującego efektu, choć fabuła ciekawa. A w tym kontekście przypomniało mi się, że z badań (chyba psychologii pozytywnej) wynika, że dzieci (ogólnie, niekoniecznie własne) - patrzenie na nie, słuchanie ich śmiechu itd. itp. łagodzą, naturalny u każdego, lęk przed śmiercią. Wyobrażam sobie, że być może faktycznie byłoby ciężko żyć w świecie samych dorosłych ludzi... (albo każdy miałby kotka lub pieska lub inne małe, pocieszne, naiwne i niewinne zwierzątko) :)

**Comment by muliasz** [comment]
Zastanawiam się, w jak dużym stopniu można odnieść do ludzi wyniki eksperymentu Calhouna, czyli tzn. eksperymentu „Mysiej Utopii”, przeprowadzonego na małej populacji myszy. Już tłumaczę, o co chodzi. 

W eksperymencie tym zapewniono myszom doskonałe warunki życia, nie brakowało im przestrzeni, schronienia, wody ani pożywienia. Żyły one w świecie pozbawionym zagrożeń - bez drapieżników, chorób itp. Jak można się spodziewać liczebność populacja, której zapewniono podobne warunki życia zaczęła gwałtownie rosnąć. O dziwo, po pewnym czasie (mimo, że zasobów nie brakowało) populacja zaczęła maleć by po pewnym czasie wymrzeć zupełnie. Po początkowym okresie gwałtownych dążeń do wykorzystania zasobów, a następnie ich optymalnego wykorzystywania, nastąpił okres stagnacji, a potem powolnego wymierania. 

Najciekawsze wydają mi się w tym przypadku, obserwowane przez badaczy, zachowania samych zwierząt. Przede wszystkim   zaobserwowano wzrost liczby zachowań agresywnych oraz postępujące zaburzenia w zakresie „mysich” zachowań seksualnych oraz ich zdolności do wychowywania młodych. W populacji pojawiło się coraz więcej wycofanych seksualnie (czasem także społecznie) osobników płci męskiej. Samice stały się za to bardziej agresywne, i często nie wykazywały instynktu macierzyńskiego. Zaobserwowano generalny spadek liczby zapłodnień, a ewentualne ciąże były wchłaniane przez organizm samicy. Młode, które pojawiały się sporadycznie, były zaniedbywane, atakowane i zmuszane do wczesnego opuszczenia gniazda.

Generalnie nie chcę wysnuwać zbyt zaawansowanych wniosków, bo eksperyment był i jest kontrowersyjny. Do tego przeprowadzano go tylko na gryzoniach i jakoś nikt nie kłopotał się zbytnio problemem chowu wsobnego i możliwością łączenia wyników eksperymentu ze zwyczajną degeneracją genetyczną populacji, to jednak wydaje mi się, że w eksperymencie tym możemy doszukiwać się przynajmniej części odpowiedzi, dlaczego aktualnie obserwujemy to, co obserwujemy.

Możliwe, że nie jest tak, że ewoluujemy w kierunku zaniedbywania naturalnego instynktu do przedłużania naszego gatunku, a raczej – paradoksalnie – jesteśmy ofiarami własnej pogoni za dobrobytem. Zauważmy, że problem dotyczy przede wszystkim krajów bogatych, w których teoretycznie panują najlepsze możliwe warunki do rozmnażania się. W krajach, gdzie życie, to codzienna walka o przetrwanie, dzieci jakoś nie brakuje. (Możemy oczywiście twierdzić, że to tylko kwestia braku wiedzy o tym, skąd się biorą dzieci oraz chociażby minimalnej wiedzy na temat (nawet tylko naturalnej) antykoncepcji).

Może poniosła mnie fantazja, ale myślę, że coś tu może być na rzeczy. Zresztą zależało mi na tym, by spojrzeć na tę kwestię z innej strony.

**Comment by mmyszkowska** [comment]
A propos wpisu Martyny chciałam dodać, że pod koniec wspomnianego eksperymentu oprócz „bezdzietnych samic” pojawili się także dbające tylko o siebie „samce pięknisie”, które całkowicie zrezygnowały z walki o dominację z innymi samcami oraz z prób zalecania się do samic. Jest to informacja o tyle istotna, że przy odrobinie wyobraźni sytuację tę można z łatwością odnieść do sytuacji panującej w niektórych bogatych krajach. Co ciekawe nie dotyczy to tylko krajów cywilizacji Zachodu, bo z podobnymi problemami mierzą się także  np. bogate kraje azjatyckie, jak: Japonia czy Korea Południowa. 

Coraz więcej kobiet zwleka tam z macierzyństwem, ponieważ z jednej strony chcą one korzystać z uroków życia, samorealizować się, a sytuację komplikuje dodatkowo fakt, że część z nich nie odczuwa w ogóle potrzeby posiadania dzieci, stąd m.in. sięganie po antykoncepcję, a jeśli nawet odczuwają one instynkt macierzyński, to problemem jest to, że coraz trudniej jest im znaleźć odpowiedzialnego partnera, zainteresowanego posiadaniem dzieci. Jeśli chodzi o mężczyzn, to np. w Japonii możemy spotkać się z całą generacją tzw. herbivore men lub grass-eater men, czyli mężczyzn wycofanych, którzy nie są zainteresowani współzawodnictwem z innymi mężczyznami czy to na polu zawodowym czy w kwestii zabiegania o partnerkę. Nagle przestają dziwić statystyki dotyczące przyrostu naturalnego w Japonii, jeśli weźmiemy pod uwagę, że ponad połowa mężczyzn w Japonii utożsamia się z grupą herbivore. (W niektórych przypadkach wycofanie mężczyzn przyjmuję tam ekstremalną formę znaną pod nazwą hikikomori, gdzie człowiek zaszywa się w domu na miesiące bądź lata, a kontakty międzyludzkie ogranicza do minimum).

Fakt, że ten wspomniane trendy stają się globalne pokazuje, że problem zmniejszonego przyrostu naturalnego, który towarzyszy bogaceniu się kraju, nie jest udziałem jednej konkretnej cywilizacji, która w pewnym momencie przestała funkcjonować jak trzeba. Raczej musimy pogodzić się z możliwością, że podobna sytuacja będzie udziałem każdej cywilizacji, która osiągnie pewien konkretny poziom rozwoju i dobrobytu.

**Comment by mgrzebalski** [comment]
@muliasz Wydaje mi się, że bardzo istotne w badaniu Calhouna była ograniczona przestrzeń życiowa gryzoni. To znaczy miały one nieograniczone zasoby, ale za małą powierzchnię do egzystencji w przeliczeniu na pojedynczego osobnika populacji. Wydaje się, więc, że przy nieograniczonych zasobach w warunkach ograniczonej przestrzeni życiowej gryzonie nie są zobligowane w jakiś sposób do adaptacyjnych zachowań jak wspomniane przez Was dominacja samców o względy samic czy naturalne odruchy macierzyńskie; brak konieczności zmagania się z trudami zapewniającymi przetrwanie i przedłużenie linii gatunku, a więc brak konieczności obejmowania określonych ról społecznych zapewniających byt skazuje populację na śmierć (mogę się też mylić, bowiem nie doszukałem się w końcu, czy aby na pewno w warunkach nieograniczonej przestrzeni życiowej również przy nieograniczonych dobrach populacja gryzoni z czasem wymiera).
Odnośnie ról społecznych zwierząt, nasuwa mi się treść bardzo ciekawego wykładu, który odbył się w tym roku na Tygodniu Mózgu w Warszawie. Prof. dr hab. Ewa J. Godzińska opowiadała o neuroetologii mrówek oraz pszczół. Co ciekawe, pomijając fascynujące zachowania mrówek jak migrowanie po różnych regionach świata celem podbicia cudzej (w obrębie jak i poza obrębem gatunku) oraz poszerzenia własnej kolonii, oddzielanie się różnych skonfliktowanych kolonii celem nieagresji czy tworzenie specyficznych form organizacji życia społecznego jak np. "adoptowanie" przez królestwo jednej bądź nawet kilku królowych, to zachowania pszczół najbardziej mnie zaskoczyły. Mianowicie pszczoły grupują się w swojej kolonii według wieku - wiele ról społecznych jak odchowywanie młodych jest przeznaczonych dla określonej grupy wiekowej. Okazuje się jednak, że czasami starsze osobniki w populacji na potrzeby przetrwania kolonii są w stanie przejąć role przypisane dla osobników młodszych - jak wspomniane odchowywanie dzieci przez robotnice, czy zbieranie pyłku przez zbieraczki itp. Co bardzo zaskakujące dochodzi u tych starszych osobników do zahamowania degeneracji układu nerwowego w związku z przyjmowaniem nazwijmy to "minionych" ról, a także upodobnienia budowy anatomicznej struktur w organizmach starszych pszczół do budowy anatomicznej pszczół młodych. Być może więc klucz do "wiecznej młodości" leży w eksplorowaniu zachowań społecznych owadów.

**Comment by Karolinaaa** [comment]
Myślę, że tylko w pewnym stopniu możemy odnieść badanie Calhouna do ludzi. Tak jak Marcin wspomniał, problemu bym się upatrywała w ograniczonej przestrzeni życiowej myszy co powodowało w pewnym momencie przeludnienie. Jednak ludzie to bardziej skomplikowana machineria. Odnosząc to do ludzi, możemy stwierdzić, że brak miejsca na prywatność czy intymność wywołuje wyższy poziom stresu i załamania interakcji społecznych, czego następstwem może być brak chęci do posiadania potomstwa. Przyczyn jednak może być wiele i ciężko stwierdzić jednoznacznie co jest przyczyną niskiego przyrostu naturalnego.
