### ISSUE TITLE
Tydzień 02 10.03-17.03

### ISSUE THREAD

**Issue by jourix** [mmagnuski/kognizastoneur#3]
Konwersator klasowy - Justyna (Soon, Brass, Heinze & Haynes (2008) Unconscious determinants of free decisions in the human brain)

**Comment by mmagnuski** [comment]
Aha - istotna informacja jest taka, że do tego tematu dojdzie jeszcze jakiś bardziej filozofujacy tekst.

**Comment by wzanczak** [comment]
Ja chętnie przygotuję prezentacje ( o ile dobrze zrozumiałam, ma być to krótkie omówienie artykułu w tej tematyce? )

**Comment by mmagnuski** [comment]
@wzanczak: nie musi być artykuł, ale tak chyba najlepiej. Gdybyś miała inny pomysł (np. jakieś zgadnienie związane z tematem) to można rozważyć.

**Comment by wzanczak** [comment]
@mmagnuski: w takim razie jeszcze się zastanowię nad tematem.
