### ISSUE TITLE
Tydzien 3

### ISSUE THREAD

**Issue by muliasz** [mmagnuski/kognizastoneur#4]
Ja i Magda Myszkowska chcialybysmy zrobić prezentacje o ewolucji (17.03?) Nie wiem czy zglosiłam to w dobrym miejscu, ale troche się pogubilam :)

**Comment by mmagnuski** [comment]
Jest ok!

**Comment by oborkowska** [comment]
Chciałabym być strażnikiem klasowym w tym tygodniu :)

**Comment by mmagnuski** [comment]
Na wszelki wypadek się upewniam: "w tym" tzn w trzecim nie w tym, który jest obecnie (koniec 1 / początek drugiego)

**Comment by oborkowska** [comment]
Tak, w tym tzn w trzecim, czyli strażnikiem klasowym na zajęciach dnia 17 marca
