### ISSUE TITLE
Zapisy na role

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/kognizastoneur#9]
Aby uniknąć gąszczu wątków - każdy na oddzielne zajęcia - przenoszę tutaj zapisy do ról.
Dziś jeszcze zgrupuję wszystkie zajęte terminy tutaj w tabelce.

**Comment by mmagnuski** [comment]
Może nie tabelka, ale chyba wszystko jest:

## Tydzień 1

Strażniczki klasowe
- Kingę Mortas
- Sylwię Grabowską

Strażniczki platformy
- Kaję Toczyską
- Maję Ulińską

Prezenterzy:
- Karolinę Kasprzak
- Pawła Kałwińskiego

## Tydzień 2

Strażniczki klasowe:
- Kaja Toczyska
- Żurawska Justyna

Strażnicy platformy:
- Myszkowska Magdalena
- Łęgowski Aleksander

Prezenterki:
- Zańczak Weronika
- Mortas Kinga

## Tydzień 3

Strażnicy klasowi:
- Olga Borkowska
- 

Strażnicy platformy:
- 
- 

Prezenterki:
- Martyna Uliasz
- Myszkowska Magda

## Tydzień 4

Strażnicy klasowi:
- 
- 

Strażnicy platformy:
- Olga Borkowska
- 

Prezenterzy:
- 
- 

## Tydzień 5

Strażnicy klasowi:
- 
- 

Strażnicy platformy:
- 
- 

Prezenterzy:
- Martyna Uliasz
- 

## Tydzień 6

Strażnicy klasowi:
- 
- 

Strażnicy platformy:
- 
- 

Prezenterzy:
- 
- 

## Tydzień 7

Strażnicy klasowi:
- 
- 

Strażnicy platformy:
- 
- 

Prezenterzy:
- 
-

**Comment by mulinska** [comment]
Wraz z @alegowski zgłaszamy się na prezenterów w 4 tygodniu

**Comment by mmagnuski** [comment]
ok!

**Comment by sgrabowska** [comment]
zgłaszam się na strażnika platformy w 4 tygodniu

**Comment by wzanczak** [comment]
Zgłaszam się do wnikliwego przeczytania literatury na najbliższe zajęcia ( 14.04)

**Comment by wzanczak** [comment]
@mmagnuski jakbyś mógł wstawić materiały, to będę wdzięczna :)

**Comment by mmagnuski** [comment]
A, jasne, zapomniałem o tym. Są dwa artykuły. Jeden jest w sylabusie. Za
chwilę wszystko wrzucę.

2016-04-11 23:37 GMT+02:00 Weronika notifications@github.com:

> @mmagnuski https://github.com/mmagnuski jakbyś mógł wstawić materiały,
> to będę wdzięczna :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mmagnuski/kognizastoneur/issues/9#issuecomment-208573480

## 

---

**Comment by sgrabowska** [comment]
Zgłaszam się na prezentera w tygodniu 4. Tylko poprosiłabym o podpowiedź na temat jakiego artykułu mogę "prezentować".

**Comment by mmagnuski** [comment]
Tydzień 04 jest już za Nami - chodzi Ci pewnie o tydzień 05, tak?

W dniu 12 kwietnia 2016 07:28 użytkownik sgrabowska <
notifications@github.com> napisał:

> Zgłaszam się na prezentera w tygodniu 4. Tylko poprosiłabym o podpowiedź
> na temat jakiego artykułu mogę "prezentować".
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/mmagnuski/kognizastoneur/issues/9#issuecomment-208713612

## 

---

**Comment by sgrabowska** [comment]
Tak, tak, 5 tydzień. Coś źle wyliczyłam przy którym tygodniu jesteśmy.

**Comment by sgrabowska** [comment]
@mmagnuski proszę o przepisanie mnie na prezentację w tygodniu ostatnim. Za późno się zgłosiłam na 5.

**Comment by muliasz** [comment]
@mmagnuski Zgłaszam się do roli strażniczki platformy w 6. tygodniu. Jako że ostatnio poprzesuwały się nam terminy, byłabym wdzięczna za informację kiedy dokładnie zaczyna się 6. tydzień platformy. (Btw… co z dyskusją przewidzianą na tydzień 5.?)

**Comment by jourix** [comment]
@mmagnuski czy mogę przygotować prezentację z zajęć 06 - deep learning?

**Comment by mmagnuski** [comment]
Hej, jasne - prezentacja ok.
Dyskusje możecie prowadzić teraz niezależnie od oficjalnych terminów, bo jesteśmy po ostatnich zajęciach.
Napiszę jeszcze w tym tygodniu do wszystkich z prognozami zaliczeń itp.
